name: AdvancedMLGRush
main: net.skillcode.advancedmlgrush.MLGRush
version: 1.0
api-version: "1.13"
author: SkillCode
commands:
  build:
    aliases:
      - buildmode
  setspawn:
  setupmap:
    aliases:
      - setupmaptemplate
      - setuptemplate
      - createmap
      - setup