name: AdvancedMLGRush
main: net.skillcode.advancedmlgrush.MLGRush
version: 3.0.1.6
author: SkillCode
website: https://skillplugins.com
api-version: "1.13"
softdepend: [ PlaceholderAPI ]
commands:
  build:
    aliases:
      - buildmode
  setspawn:
  setupmap:
    aliases:
      - setupmaptemplate
      - setuptemplate
      - createmap
      - setup
  quit:
    aliases:
      - leave
      - l
  queue:
  settings:
  spectate:
  gadgets:
  stats:
