name: AdvancedMLGRush
main: net.skillcode.advancedmlgrush.MLGRush
version: 1.0
author: SkillCode
api-version: "1.13"
commands:
  build:
    aliases:
      - buildmode
  setspawn:
  setupmap:
    aliases:
      - setupmaptemplate
      - setuptemplate
      - createmap
      - setup
  quit:
    aliases:
      - leave
      - l